name: test-coverage
on:
  push:
    branches: [ main, code-climate-test-coverage ]

jobs:
  test:
    name: Code-Climate-Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
steps:
  - name: Test & publish code coverage
    uses: paambaati/codeclimate-action@v2.7.5
    env:
      CC_TEST_REPORTER_ID: ${{secrets.CodeClimate}}
    with:
      coverageCommand: npm test
      debug: true